import { query } from '../db/pool.js';
import { sendEmail } from '../integrations/email.js';
import { logger } from '../utils/logger.js';

// Weekly digest: high-risk activity + review load + revert rate.
export async function buildDigest(orgId) {
  const [tiers, topRisky, reverts, load] = await Promise.all([
    query(
      `SELECT s.tier, COUNT(*)::int AS n FROM pull_requests p
         JOIN repos r ON r.id = p.repo_id
         JOIN LATERAL (SELECT tier FROM pr_risk_scores WHERE pr_id=p.id ORDER BY scored_at DESC LIMIT 1) s ON true
        WHERE r.org_id=$1 AND p.opened_at > now() - interval '7 days'
        GROUP BY s.tier`, [orgId]),
    query(
      `SELECT p.number, p.title, r.full_name AS repo, s.tier, s.score
         FROM pull_requests p JOIN repos r ON r.id=p.repo_id
         JOIN LATERAL (SELECT tier, score FROM pr_risk_scores WHERE pr_id=p.id ORDER BY scored_at DESC LIMIT 1) s ON true
        WHERE r.org_id=$1 AND p.state='open' AND s.tier IN ('high','critical')
        ORDER BY s.score DESC LIMIT 10`, [orgId]),
    query(
      `SELECT COUNT(*) FILTER (WHERE o.reverted)::int AS reverts,
              COUNT(*)::int AS merges
         FROM pull_requests p JOIN repos r ON r.id=p.repo_id
         LEFT JOIN pr_outcomes o ON o.pr_id=p.id
        WHERE r.org_id=$1 AND p.merged_at > now() - interval '7 days'`, [orgId]),
    query(
      `SELECT login, COUNT(*)::int AS open_reviews FROM (
         SELECT unnest(p.requested_reviewers) AS login
           FROM pull_requests p JOIN repos r ON r.id=p.repo_id
          WHERE r.org_id=$1 AND p.state='open'
       ) t GROUP BY login ORDER BY open_reviews DESC LIMIT 5`, [orgId])
  ]);

  const html = renderDigestHTML({
    tiers: tiers.rows,
    topRisky: topRisky.rows,
    reverts: reverts.rows[0],
    load: load.rows
  });
  return { html, subject: `Meridian — weekly review digest` };
}

export async function sendWeeklyDigest(orgId) {
  const { rows } = await query(
    `SELECT digest_recipients FROM org_settings WHERE org_id=$1`, [orgId]);
  const recipients = rows[0]?.digest_recipients || [];
  if (!recipients.length) {
    logger.info({ orgId }, 'digest_skipped_no_recipients');
    return;
  }
  const { html, subject } = await buildDigest(orgId);
  for (const to of recipients) {
    await sendEmail({ to, subject, html });
  }
}

function renderDigestHTML({ tiers, topRisky, reverts, load }) {
  const tierRow = tiers.map(t => `<td style="padding:6px 12px"><b>${t.tier}</b>: ${t.n}</td>`).join('');
  const riskyList = topRisky.map(r =>
    `<li><code>${r.repo}</code> #${r.number} — ${escape(r.title)} <span style="color:#c00">[${r.tier} ${r.score}]</span></li>`
  ).join('');
  const loadList = load.map(l => `<li>${l.login}: ${l.open_reviews} open</li>`).join('');
  const revertPct = reverts?.merges ? ((reverts.reverts / reverts.merges) * 100).toFixed(1) : '0.0';
  return `<!doctype html><html><body style="font-family:ui-sans-serif,system-ui;background:#0b0d10;color:#e6e8eb;padding:24px">
    <h1 style="font-family:'Instrument Serif',Georgia,serif;font-weight:400;font-size:28px;margin:0 0 8px">This week in review</h1>
    <div style="color:#8b93a0;margin-bottom:24px">Generated by Meridian</div>
    <table><tr>${tierRow}</tr></table>
    <h2 style="margin-top:24px">Top open high-risk PRs</h2>
    <ul>${riskyList || '<li>none</li>'}</ul>
    <h2>Revert rate</h2>
    <p>${reverts?.reverts || 0} reverts of ${reverts?.merges || 0} merges (${revertPct}%)</p>
    <h2>Reviewer load</h2>
    <ul>${loadList}</ul>
  </body></html>`;
}
function escape(s) { return String(s).replace(/[<>&]/g, c => ({'<':'&lt;','>':'&gt;','&':'&amp;'}[c])); }
